name: xarray-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - numpy
  - scipy
  - xarray
  - dask
  - scikit-learn
  - ipython
  - sphinx
  - numpydoc
  - sphinx-gallery
  - sphinx_rtd_theme
  - pip
